services:
  www:
    build: .
    ports:
      - "81:80" 
    volumes:
      - ./public:/var/www/html/
    depends_on:
      - db
  db:
    image: mariadb:11.7.2
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: db_ejm1
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1.pa55
      MYSQL_ROOT_PASSWORD: root.pa55
    volumes:
      - ./base_datos/patito.sql:/docker-entrypoint-initdb.d/patito.sql 
      - ./mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.1
    depends_on:
      - db
    ports:
      - "8081:80" 
    environment:
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1.pa55
      MYSQL_ROOT_PASSWORD: root.pa55